name: 'Dokploy Application Push trigger'
description: 'Trigger a Dokploy application deployment'
branding:
  icon: 'upload-cloud'
  color: 'gray-dark'
inputs:
  DOKPLOY_URL:
    description: 'Dokploy base URL, e.g. https://dokploy.com'
    required: true
  DOKPLOY_AUTH_TOKEN:
    description: 'Dokploy authentication token'
    required: true
  DOKPLOY_APP_ID:
    description: 'Dokploy application ID'
    required: true
runs:
  using: "composite"
  steps:
    - name: Trigger Dokploy deployment
      shell: bash
      env:
        URL: ${{ inputs.DOKPLOY_URL }}
        AUTH_TOKEN: ${{ inputs.DOKPLOY_AUTH_TOKEN }}
        APPLICATION_ID: ${{ inputs.DOKPLOY_APP_ID }}
      run: |
        response=$(curl -X 'POST' \
          "$URL/api/application.deploy" \
          -H 'accept: application/json' \
          -H 'Content-Type: application/json' \
          -H "Authorization: Bearer $AUTH_TOKEN" \
          -d "{\"applicationId\": \"$APPLICATION_ID\"}" \
          -w "%{http_code}" \
          -o /dev/null \
          -s)
        
        if [ "$response" -ne 200 ]; then
          echo "Deployment failed with status code: $response"
          exit 1
        fi
